[package]
name = "vrrb-config"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitives = { path = "../primitives" }
secp256k1 = { version = "0.20.2", features = ["rand"] }
