[package]
name = "wasm_cli"
description = "VRRB developer CLI and WASM runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
wasm_loader = { workspace = true }
wasm_runtime = { workspace = true }
telemetry = { workspace = true }
