[package]
name = "reward"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
primitives = { workspace = true }
vrrb_core = { workspace = true }
