[package]
name = "storage"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vrrbdb = { workspace = true }
storage_utils = { workspace = true }
serial_test = { workspace = true }
ethereum-types = { workspace = true }
integral-db = { workspace = true }
anyhow = { workspace = true }
parking_lot = { workspace = true }