[package]
name = "vrrbdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
sha2 = { workspace = true }
secp256k1 = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
vrrb_core = { workspace = true }
primitives = { workspace = true }
patriecia = { workspace = true }
parking_lot = { workspace = true }
bincode = { workspace = true }
storage_utils = { workspace = true }
rocksdb = { workspace = true }
serde_json = { workspace = true }
serial_test = { workspace = true }
telemetry = { workspace = true }
ethereum-types = { workspace = true }
integral-db = { workspace = true }
microkv = { workspace = true }
hex = { workspace = true }
block = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
