[package]
name = "primitives"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
hbbft = { workspace = true }
secp256k1 = { workspace = true }
serde_json = { workspace = true }
jsonrpsee = { workspace = true }
kademlia-dht = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
sha3 = { workspace = true }
