[package]
name = "vrrb_vrf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vrf = "0.2.4"
rand_chacha = "0.3.1"
hex = "0.4.3"
rand = "0.8.5"
rand_core = "0.6.3"
parity-wordlist = "1.3.1"
vrrb_core = { workspace = true }
primitives = { workspace = true }
