[package]
name = "wasm_runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
derive_builder = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
telemetry = { workspace = true }
wasmer = { workspace = true }
wasmer-wasix = { workspace = true }
wasmer-wasix-types = { workspace = true }
vrrb_core = { workspace = true }
