[package]
name = "quorum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vrrb_core = { workspace = true }
block = { workspace = true }
vrrb_vrf = { workspace = true }
rand_chacha = { workspace = true }
format-bytes = { workspace = true }
thread_local = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
sha256 = { workspace = true }
hex = { workspace = true }
primitives = { workspace = true }
serde = { workspace = true }
ethereum-types = { workspace = true }
